### ISSUE TITLE
Music is not working

### ISSUE THREAD

**Issue by kegri** [corpnewt/CorpBot.py#100]
Hi, recently I forked CorpBot. I'm configuring the CorpBot's Music.py Cog with my lavalink server host but it say's that it can't find the video, how can I solve this? (it can't play youtube url too)

for example my lavalink server thing:

`node = self.bot.wavelink.get_best_node() if not node: node = await self.bot.wavelink.initiate_node(host='lava.xxxxxxx.host', port=2333, rest_uri='http://lava.xxxxxx.host:2333/', password='xxxxxxx', identifier='Kegri', region='us_central')`

**Comment by heartbrokens** [comment]
for example my lavalink server thing:

`		node = self.bot.wavelink.get_best_node()
		if not node:
			node = await self.bot.wavelink.initiate_node(host='lava.xxxxxxx.host',
				port=2333,
				rest_uri='http://lava.xxxxxx.host:2333/',
				password='xxxxxxx',
                identifier='Kegri',
				region='xxxxxxx.host')`
