### ISSUE TITLE
Reddit - Whoops! I couldn't find a working link.

### ISSUE THREAD

**Issue by aerothan** [corpnewt/CorpBot.py#101]
Any reddit command returns the same error.

**Comment by corpnewt** [comment]
I just tested on my instance and it works fine.  Perhaps you've been rate-limited by reddit for attempting too many api calls?

-CorpNewt

**Comment by aerothan** [comment]
Found the issue, Looks to be a change with python 3.9 in removing HTML Parser unescape
AttributeError: 'HTMLParser' object has no attribute 'unescape'

**Comment by corpnewt** [comment]
Hmmm - if I get time, I'll look into working around that.  I'll leave this issue valid until then though.

-CorpNewt
