### ISSUE TITLE
Face.py commands let users mention roles they lack permissions to mention.

### ISSUE THREAD

**Issue by im-not-a-dev** [corpnewt/CorpBot.py#103]
If a user runs one of the commands belonging to in any case Face.py, and potentially other cogs with a handmade role tag behind it ie. `$lenny <@123421>` the bot will then ping that role in the output if it has permission to do so, even if the original user didn't.

This can easily lead to massive mass-mentions in servers.

**Comment by corpnewt** [comment]
This should be fixed with the Nullify rework [here](https://github.com/corpnewt/CorpBot.py/commit/34ab44241cebce96daa938bbc6576cb02fb868f2#diff-2f28879eec3baba26faf8a5fcc2e2a39b6ea2d4abba704bc6bd500d138c0f1dc).

-CorpNewt
