### ISSUE TITLE
CAH cog issue. 

### ISSUE THREAD

**Issue by JimJamGo** [corpnewt/CorpBot.py#105]
This issue is very similar to "Cards against humanity cog question #42" from BleuSkie.

I have been using CorpBot for a while now and it's great. I used to use the CAH cog all the time but now it's not working. I found out that the deck.json was missing so I redownloaded it from the linked website but that still seems to have the same issue, a keyword error for whiteCards. I had a look into the json and found that there was no mention of whiteCards, the closest I could find was white. From this I assume the format has changed. Thankfully I was able to find an old version of it in the Issue report mentioned at the start, however when trying to run with that file it still doesn't work. Any help would be greatly appreciated! 

Thanks for making such a great bot available to others! 

Here is the error if it helps:
![image](https://user-images.githubusercontent.com/30004589/106328554-ec4c8480-6277-11eb-8d11-ea652ab3f62c.png)

**Comment by corpnewt** [comment]
Hey there - I should have some time later today to look into this. If it's simply that the file structure changed, it shouldn't be too hard to fix.

-CorpNewt

**Comment by corpnewt** [comment]
Should be fixed as of [this commit](https://github.com/corpnewt/CorpBot.py/commit/9143aeaf6a3e7528fc91776f98cc2eb0957e7b3a).  Note that it does require you use the compact.json option when downloading the cards.

-CorpNewt
