### ISSUE TITLE
Claiming the Bot

### ISSUE THREAD

**Issue by eunola** [corpnewt/CorpBot.py#108]
I can’t seem to claim my bot. I use the command and it responds that it’s been claimed but when I go and use a command that requires owner the bot responds saying it hasn’t been claimed

**Comment by corpnewt** [comment]
Hey there - which branch of the bot are you using?

If you're using the `rewrite` branch, you can try claiming the bot, then using the `$flush` command to force-flush the settings to disk.  If you're on the `redis` branch, you may need to make sure that your redis db is setup and functioning properly.  I just tested both branches on my beta bot - and the only issue I ran into was with using the `$shutdown` or `$reboot` commands in the `rewrite` branch not dumping the current settings - however, this would not affect whether or not the command sets things in memory.  I'll have to look into fixing that - perhaps I could just invoke the flush command within the shutdown/reboot commands first.  Either way, claiming the bot should yield access to the owner commands immediately after per my testing.

-CorpNewt

***

I just pushed [a commit](https://github.com/corpnewt/CorpBot.py/commit/a41fc61bd0e86db8e9d406ae917b36a7ada99568) (both to the `rewrite` and `redis` branches) that will invoke the `flush()` command before shutting down/rebooting which should fix the issue I outlined above (I also fixed an issue with `$shutdown`).  Beyond that - I'm not sure where your instance may be having problems outside something not working correctly regarding saving settings.

**Comment by eunola** [comment]
Thank you I’ll try to flush to disk and the the other way if it doesn’t work

**Comment by eunola** [comment]
It’s working now apparently I had some typos

**Comment by corpnewt** [comment]
Sounds good, I'll close the issue.

-CorpNewt
