### ISSUE TITLE
Cogs

### ISSUE THREAD

**Issue by omsenjalia** [corpnewt/CorpBot.py#110]
Hey where can I find additional cogs (or I cant?) And can I have a discord server link too I cannot find it on your reddit ty

**Comment by corpnewt** [comment]
Hey there,

All of the cogs I have written are in this repo - I'm not aware of any others out in the wild.  As for a discord server link, in your [prior issue](https://github.com/corpnewt/CorpBot.py/issues/109), I linked the invite for the /r/Hackintosh discord server.  I'll link that again  [here](https://discord.gg/u8V7N5C).

-CorpNewt
