### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by IrishAU** [corpnewt/CorpBot.py#113]
Where do I get my weather and currency API from?
![image](https://user-images.githubusercontent.com/84210026/118353047-02bce880-b5a8-11eb-91cf-7758ec366c74.png)

**Comment by aerothan** [comment]
weather = https://home.openweathermap.org/api_keys

I dont use the convert function, thus never setup an API for currency. However a quick google search will find you on your way.

**Comment by corpnewt** [comment]
As aerothan mentioned, you can get the weather api key from https://openweathermap.org/api, and you can get the currency conversion key from https://free.currencyconverterapi.com

-CorpNewt
