### ISSUE TITLE
Resetting Bot Presence

### ISSUE THREAD

**Issue by eunola** [corpnewt/CorpBot.py#119]
I was trying to remove the bot set custom status but I can’t seem to find a way to do so. I’ve shutdown the bot and restarted it.

**Comment by corpnewt** [comment]
You can use the bot's `$pres` command to change its presence:
```
Changes the bot's presence (owner-only).

Playing type options are:

0. Playing (or None without game)
1. Streaming (requires valid twitch url)
2. Listening
3. Watching

Status type options are:

1. Online
2. Idle
3. DnD
4. Invisible

If any of the passed entries have spaces, they must be in quotes.
```
Passing nothing to the command resets any playing status, and changes the bot to online.  Examples below:

![image](https://user-images.githubusercontent.com/12772521/123436333-222a3680-d594-11eb-8af2-3c621b191b7a.png)


-CorpNewt
