### ISSUE TITLE
Conform to PEP 8

### ISSUE THREAD

**Issue by AM2i9** [corpnewt/CorpBot.py#120]
The current naming conventions and indentations in your code are not at all very nice.

Please read this:
https://www.python.org/dev/peps/pep-0008/

**Comment by camielverdult** [comment]
no u

**Comment by sasdallas** [comment]
Coders may write code as they feel it should be written, at least that's what I believe.

**Comment by kernel-dev** [comment]
Why? So we can have another Linux moment?
