### ISSUE TITLE
discord.py no longer updated

### ISSUE THREAD

**Issue by EunolaSims4** [corpnewt/CorpBot.py#130]
This isn't really an issue at least I don't think but disord.py will no longer be updated or maintained and I was wondering if it would effect the bot in any way?

**Comment by SomeRandomGuy009** [comment]
> This isn't really an issue at least I don't think but disord.py will no longer be updated or maintained and I was wondering if it would effect the bot in any way?

discord.py maintenance started again if u didn't know

**Comment by corpnewt** [comment]
Worth mentioning too that pycord was a drop-in replacement until rapptz decided to continue development of discord.py.

-CorpNewt
