### ISSUE TITLE
Lavalink Error

### ISSUE THREAD

**Issue by EunolaSims4** [corpnewt/CorpBot.py#140]
I keep getting this error when I try and play something on a voice channel. The hot also doesn't seem to appear in the voice channel even using the join/summon command. 

Connection Failure: Cannot connect to host 127.0.0.1:2333 ssl:default [The remote computer refused the network connection]
Error resolving search:
ClientConnectorError(ConnectionKey(host='127.0.0.1', port=2333, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None))

I also got these errors

Loading CogManager...
Connecting to database on localhost:27017...
Connection failed, trying JSON
Since no mongoDB instance was running, I'm reverting back to the Settings.json
Loading brain from standard.brn...done (97002 categories in 14.62 seconds)
Kernel bootstrap completed in 14.63 seconds
Missing idgbkey - skipping.
Loaded 105 of 105 cogs.
Ignoring exception in on_all_shards_ready
Traceback (most recent call last):
  File "C:\Users\shaki\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\shaki\OneDrive\Documents\MesdusaBot---d.py\Main.py", line 88, in on_all_shards_ready
    await return_message()
NameError: name 'return_message' is not defined
--

Trying to update via git...

fatal: unable to access 'https://github.com/EunolaSims4/MesdusaBot---d.py.git/': Could not resolve host: github.com

**Comment by EunolaSims4** [comment]
And when it does finally connect I get a try using more specific search terms, or pass a url when I use a YouTube link

**Comment by corpnewt** [comment]
Is this some modified version of the bot?  Your Main.py module does not line up with what's in this repo.  For instance, with line 88, yours has `await return_message()`, mine has a comment within the `on_ready()` event handler (as seen [here](https://github.com/corpnewt/CorpBot.py/blob/rewrite/Main.py#L88)).  You can also see the `return_message()` function definition in [lines 64-83](https://github.com/corpnewt/CorpBot.py/blob/rewrite/Main.py#L64-L83).

Not sure what code you're running, but it doesn't match the current code fo Main.py in either the rewrite or redis branches of this repo.

-CorpNewt

**Comment by EunolaSims4** [comment]
It's not. The only thing I tried to add was to have the bot status at startup. But the error was happening even before I tried adding the on ready status

**Comment by EunolaSims4** [comment]
I redid the Main.py and the return edsage cleared up but the hit still isn't working for the Music Cog, but no error message appears in the terminal.
