### ISSUE TITLE
'NoneType' object has no attribute

### ISSUE THREAD

**Issue by EunolaSims4** [corpnewt/CorpBot.py#145]
I downloaded the new build of the bot but I keep getting this error for the CogManager

C:\Users\shaki\Downloads\CorpBot.py-rewrite (2)\CorpBot.py-rewrite\Main.py:106: RuntimeWarning: coroutine 'BotBase.load_extension' was never awaited
  bot.load_extension("Cogs.CogManager")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[2022-08-25 09:34:07] [ERROR   ] discord.client: Ignoring exception in on_all_shards_ready
Traceback (most recent call last):
  File "C:\Users\shaki\OneDrive\Documents\MEGA\MesdusaBot---d.py\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\shaki\Downloads\CorpBot.py-rewrite (2)\CorpBot.py-rewrite\Main.py", line 109, in on_all_shards_ready
    cog_loaded, cog_count = cg_man._load_extension()
AttributeError: 'NoneType' object has no attribute '_load_extension'

**Comment by EunolaSims4** [comment]
I've redownloaded the build twice and still get this error

**Comment by corpnewt** [comment]
Can you send all of the logging from the bot when you try to start it? CogManager being None means something is horribly amiss.

**Comment by EunolaSims4** [comment]
That's the full error it gives me. I haven't modified Main.py in any way either.I did a fresh download of the build, changed my bots token and I still get it.

**Comment by corpnewt** [comment]
What version of python are you using - and where did you get it?  Did you make sure to install all the dependencies (via Install.bat/Install.command)?  I see that you had a similar error posted in the past - and that was likely due to your local environment, so I'd also verify that is setup properly.

I currently run multiple instances of the bot - both the rewrite and redis branches - without any of the issues you face, so I'm not sure what's causing it beyond potential environment problems.

-CorpNewt

**Comment by EunolaSims4** [comment]
i'm using 3.10 and I installed from python's website. I installed all of the dependencies.

**Comment by EunolaSims4** [comment]
It's working now in pycharm but it's giving the error on my hosting. I'm reinstalling the hosting server now

**Comment by corpnewt** [comment]
Are you running this instance from onedrive?  If so - try copying the project locally.

**Comment by EunolaSims4** [comment]
Locally

**Comment by corpnewt** [comment]
Can you run the Install.bat/command file and send the resulting text here?

**Comment by EunolaSims4** [comment]
cmd.exe /c Install.bat
  ###                ###
 # CorpBot - CorpNewt #
###                ###



Updating pycord - 1 of 21


Requirement already satisfied: py-cord[voice] in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2.1.1)
Requirement already satisfied: aiohttp<3.9.0,>=3.6.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from py-cord[voice]) (3.8.1)
Requirement already satisfied: PyNaCl<1.6,>=1.3.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from py-cord[voice]) (1.5.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord[voice]) (2.1.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord[voice]) (1.3.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord[voice]) (1.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord[voice]) (1.8.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord[voice]) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord[voice]) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord[voice]) (22.1.0)
Requirement already satisfied: cffi>=1.4.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from PyNaCl<1.6,>=1.3.0->py-cord[voice]) (1.15.1)
Requirement already satisfied: pycparser in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.4.1->PyNaCl<1.6,>=1.3.0->py-cord[voice]) (2.21)
Requirement already satisfied: idna>=2.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from yarl<2.0,>=1.0->aiohttp<3.9.0,>=3.6.0->py-cord[voice]) (2.10)


Updating certifi - 2 of 21


Requirement already satisfied: certifi in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2022.6.15)


Updating pillow - 3 of 21


Requirement already satisfied: pillow in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (9.2.0)


Updating Wavelink - 4 of 21


Requirement already satisfied: Wavelink in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (1.3.2)
Requirement already satisfied: aiohttp<4,>=3.7.4 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from Wavelink) (3.8.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<4,>=3.7.4->Wavelink) (6.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<4,>=3.7.4->Wavelink) (1.3.1)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<4,>=3.7.4->Wavelink) (2.1.1)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<4,>=3.7.4->Wavelink) (1.8.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<4,>=3.7.4->Wavelink) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<4,>=3.7.4->Wavelink) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<4,>=3.7.4->Wavelink) (22.1.0)
Requirement already satisfied: idna>=2.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from yarl<2.0,>=1.0->aiohttp<4,>=3.7.4->Wavelink) (2.10)


Updating Requests - 5 of 21


Requirement already satisfied: Requests in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2.28.1)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from Requests) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from Requests) (2022.6.15)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from Requests) (1.26.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from Requests) (2.10)


Updating parsedatetime - 6 of 21


Requirement already satisfied: parsedatetime in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2.6)


Updating psutil - 7 of 21


Requirement already satisfied: psutil in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (5.9.1)


Updating pyparsing - 8 of 21


Requirement already satisfied: pyparsing in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (3.0.9)


Updating pyquery - 9 of 21


Requirement already satisfied: pyquery in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (1.4.3)
Requirement already satisfied: cssselect>0.7.9 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pyquery) (1.1.0)
Requirement already satisfied: lxml>=2.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pyquery) (4.9.1)


Updating pyaiml - 10 of 21


Collecting git+https://github.com/paulovn/python-aiml
  Cloning https://github.com/paulovn/python-aiml to c:\users\admin\appdata\local\temp\pip-req-build-ftpo36oi
  Running command git clone --filter=blob:none --quiet https://github.com/paulovn/python-aiml 'C:\Users\Admin\AppData\Local\Temp\pip-req-build-ftpo36oi'
  Resolved https://github.com/paulovn/python-aiml to commit 21c77d5e204dfdbaef315e570fdd918b852c738b
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: setuptools in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from python-aiml==0.9.3) (65.3.0)


Updating speedtest-cli - 11 of 21


Requirement already satisfied: speedtest-cli in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2.1.3)


Updating pytz - 12 of 21


Requirement already satisfied: pytz in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2022.2.1)


Updating wikipedia - 13 of 21


Requirement already satisfied: wikipedia in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (1.4.0)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from wikipedia) (2.28.1)
Requirement already satisfied: beautifulsoup4 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from wikipedia) (4.11.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2022.6.15)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (1.26.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.10)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.1.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->wikipedia) (2.3.2.post1)


Updating googletrans (direct api branch) - 14 of 21


Collecting git+https://github.com/ssut/py-googletrans@feature/enhance-use-of-direct-api
  Cloning https://github.com/ssut/py-googletrans (to revision feature/enhance-use-of-direct-api) to c:\users\admin\appdata\local\temp\pip-req-build-pup7mehk
  Running command git clone --filter=blob:none --quiet https://github.com/ssut/py-googletrans 'C:\Users\Admin\AppData\Local\Temp\pip-req-build-pup7mehk'
  Running command git checkout -b feature/enhance-use-of-direct-api --track origin/feature/enhance-use-of-direct-api
  branch 'feature/enhance-use-of-direct-api' set up to track 'origin/feature/enhance-use-of-direct-api'.
  Switched to a new branch 'feature/enhance-use-of-direct-api'
  Resolved https://github.com/ssut/py-googletrans to commit 16418d277415300f611339d6829c11e798931e00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: httpx==0.13.3 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from googletrans==3.0.0) (0.13.3)
Requirement already satisfied: hstspreload in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from httpx==0.13.3->googletrans==3.0.0) (2022.8.1)
Requirement already satisfied: rfc3986<2,>=1.3 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from httpx==0.13.3->googletrans==3.0.0) (1.5.0)
Requirement already satisfied: sniffio in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from httpx==0.13.3->googletrans==3.0.0) (1.2.0)
Requirement already satisfied: certifi in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from httpx==0.13.3->googletrans==3.0.0) (2022.6.15)
Requirement already satisfied: chardet==3.* in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from httpx==0.13.3->googletrans==3.0.0) (3.0.4)
Requirement already satisfied: httpcore==0.9.* in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from httpx==0.13.3->googletrans==3.0.0) (0.9.1)
Requirement already satisfied: idna==2.* in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from httpx==0.13.3->googletrans==3.0.0) (2.10)
Requirement already satisfied: h11<0.10,>=0.8 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==3.0.0) (0.9.0)
Requirement already satisfied: h2==3.* in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==3.0.0) (3.2.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==3.0.0) (5.2.0)
Requirement already satisfied: hpack<4,>=3.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==3.0.0) (3.0.0)


Updating giphypop - 15 of 21


Collecting giphypop
  Cloning https://github.com/shaunduncan/giphypop.git to c:\users\admin\appdata\local\temp\pip-install-pzp8qjj9\giphypop_e076174f8f4e4b80a62224984f7bcdb6
  Running command git clone --filter=blob:none --quiet https://github.com/shaunduncan/giphypop.git 'C:\Users\Admin\AppData\Local\Temp\pip-install-pzp8qjj9\giphypop_e076174f8f4e4b80a62224984f7bcdb6'
  Resolved https://github.com/shaunduncan/giphypop.git to commit 21e7f51c4f000ae24be3805b7eeec52bcce3d390
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from giphypop) (2.28.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->giphypop) (2022.6.15)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->giphypop) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->giphypop) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->giphypop) (2.10)


Updating numpy - 16 of 21


Requirement already satisfied: numpy in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (1.23.2)


Updating pymongo - 17 of 21


Requirement already satisfied: pymongo in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (4.2.0)


Updating igdb_api_python - 18 of 21


Requirement already satisfied: igdb_api_python in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (1.0)
Requirement already satisfied: requests>=2.13.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from igdb_api_python) (2.28.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.13.0->igdb_api_python) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.13.0->igdb_api_python) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.13.0->igdb_api_python) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.13.0->igdb_api_python) (2022.6.15)


Updating geopy - 19 of 21


Requirement already satisfied: geopy in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2.2.0)
Requirement already satisfied: geographiclib<2,>=1.49 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from geopy) (1.52)


Updating pyfiglet - 20 of 21


Requirement already satisfied: pyfiglet in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (0.8.post1)


Updating regex - 21 of 21


Requirement already satisfied: regex in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2022.8.17)
Done.

Press [enter] to leave the script...

**Comment by corpnewt** [comment]
Yep - all of that looks fine.  And you said when you start the bot, it doesn't show you *anything* other than what was posted in your first message?  If there's any other logging there - please send it here.

**Comment by EunolaSims4** [comment]
That's the only logging it shows

**Comment by corpnewt** [comment]
Did you install discord.py individually at any point?  Or just through the Install.bat/command?

**Comment by corpnewt** [comment]
Yeah - I just updated all my dependencies and started up my test bot - and it worked as expected.  I did notice that the error you get is referenced in the discord.py update gist - implying you're using the wrong discord api wrapper (referenced [here](https://stackoverflow.com/questions/71504627/runtimewarning-coroutine-botbase-load-extension-was-never-awaited-after-upd) in a SO post about the same issue you get, and [here](https://gist.github.com/Rapptz/6706e1c8f23ac27c98cee4dd985c8120) from Rapptz).

I'm currently using [pycord 2.1.1](https://github.com/Pycord-Development/pycord/releases/tag/v2.1.1), and that's what the Install.bat/command will install **if** you haven't installed some standalone copy of discord.py.

-CorpNewt

**Comment by EunolaSims4** [comment]
So I need to check if discord is installed and delete that dependency?

**Comment by corpnewt** [comment]
Yes - my guess is that you have discord.py installed (which overrides the version leveraged by pycord) - which is conflicting, i.e. your local environment is still the issue.

**Comment by corpnewt** [comment]
You should be able to remove it and ensure the proper pycord version is installed via the following one at a time in cmd/terminal (make sure `python` points to the python binary you use to run the bot):
```
python -m pip uninstall discord.py
python -m pip install -U py-cord[voice]
```

The first will remove discord.py - the second will install (update) py-cord with voice support, restoring any needed discord.py related code to the proper and expected versions.

**Comment by EunolaSims4** [comment]
That's what it was! It was installing discord.py instead of py-cord for some reason

**Comment by corpnewt** [comment]
It was not - you were.  The Install.py script only installs py-cord.

**Comment by EunolaSims4** [comment]
I had built a bot with discord.py in the past so I guess it never uninstalled. But thanks for your help

**Comment by corpnewt** [comment]
np
