### ISSUE TITLE
Improve auto-tool detection

### ISSUE THREAD

**Issue by lzhoang2801** [corpnewt/CorpBot.py#149]
It was purely by chance that I saw this content, and it's going to be useless from this point onward. It's just imposing opinions without any understanding, trying to block a tool that's always striving to improve

https://github.com/corpnewt/CorpBot.py/blob/70887b240701017a6bf71f881c87757e0d31acab/Cogs/OpenCore.py#L218C3-L243C14

**Comment by lzhoang2801** [comment]
Provide a few examples to support this thoughtless change

https://github.com/lzhoang2801/OpCore-Simplify/commit/23ea6bd2071526e9faabe19460f08bb1294d0fa3
https://github.com/lzhoang2801/OpCore-Simplify/blob/main/Scripts/kext_maestro.py#L379C1-L389C15

**Comment by lzhoang2801** [comment]
Take a look and see if you can find anything unique in the configuration created by OpCore Simplify. Removing all the default entries found in sample.plist? Customizing the background of the OpenCore Picker? Using the OpenHfsPlus driver?

https://github.com/lzhoang2801/OpCore-Simplify/blob/main/Scripts/config_prodigy.py

**Comment by lzhoang2801** [comment]
Everything is public, but your actions are disappointing

**Comment by corpnewt** [comment]
There is no blocking or otherwise.  Simply a footer that gets updated.

-CorpNewt

**Comment by sean-langley** [comment]
This does not modify or break anything about OpCore Simply or prevent a person from using it, it simply allows for the detection of the use of automation to write EFIs. It is still up to the individuals attempting to support (or not support) these tools to determine how they want to action that knowledge.

**Comment by lzhoang2801** [comment]
Everyone tends to foolishly blame ACPI errors on ACPI itself, when they could actually stem from a range of issues involving PCI, CPU, and more. A clear example of this can be found here: https://osxinfo.net/konu/otomatik-efi-olusturucu.31654/post-223326

**Comment by corpnewt** [comment]
This is an issue thread for a discord bot which does not interpret ACPI tables, nor attempt to solve/answer related questions about it.  While I agree that people often misdiagnose issues when attempting to help, that holds little relevance in this issue thread.

-CorpNewt

**Comment by lzhoang2801** [comment]
It seems that people are just good at sending messages on Discord, but I'm not sure how much real experience they have. Most of the time, they just follow along with criticism about any given issue. Even if the same setup as Dortania causes issues, they still criticize OpCore Simplify. I’m an example of someone who doesn't get involved but is trying to endure this

**Comment by corpnewt** [comment]
Creating and releasing any tool to an established community will inevitably be met with some criticism, though I feel you are misdirecting your frustrations here.  The bot does not block, alter, or deny anything from a plist sent to its `$plist` function - but merely attempts to note the possibility known tools were used in its creation/editing.

-CorpNewt
