### ISSUE TITLE
Cards against humanity cog question

### ISSUE THREAD

**Issue by BleuSkie** [corpnewt/CorpBot.py#42]
Hello. I am unsure how the cog works. I get a no white card error and invalid form body when I try to run commands for the cog like $hand and $addbot. I saw you needed a deck list, but that didn't seem to download with the rest of the bot. I did see the site in the code and made a deck.json file for it, but I am unsure of the formating. I am entirely new to this and that could be my problem. Could you give me a little insight? Thanks. (Sorry if this is a dumb question)

![cah](https://user-images.githubusercontent.com/34435330/33819666-9533c446-de19-11e7-996e-973fcdb85214.PNG)

**Comment by corpnewt** [comment]
Hey there - sorry the deck.json info is kinda buried - it's actually in one of [the comments](https://github.com/corpnewt/CorpBot.py/blob/rewrite/Cogs/CardsAgainstHumanity.py#L47) at line 47 in the cog.  You just need to go to http://www.crhallberg.com/cah/json to generate the json data, then save it as deck.json in the main project folder.  I didn't include the deck as I thought it might leave things more open as you can select which decks and such you'd like to use.  Hopefully that helps!  Let me know if you have other questions.

**Comment by BleuSkie** [comment]
Wow, thanks for the quick reply. I really appreciate it. And yeah, it was buried a bit deep, but I did find that site in the code and got the file before I opened this question.

![cah1](https://user-images.githubusercontent.com/34435330/33821067-74154fd0-de20-11e7-9ab6-b2cb74834136.PNG)
![cah2](https://user-images.githubusercontent.com/34435330/33821074-77c61308-de20-11e7-925b-74f7ac8275df.PNG)

The  earlier errors happened after, so I thought I might have to format the json file a specific way?

**Comment by corpnewt** [comment]
Hmmmm - I just did select-all, copy, then paste for mine.  As long as the site didn't change their format, it should all be the same.  IIRC (as it's been a bit since I've worked on that code), there are 2 main lists, "blackCards" and "whiteCards".  As long as you have those two, it should work correctly.  If you can't figure it out, though, I'll add my deck.json to the code.

**Comment by BleuSkie** [comment]
Yep, select all and copy and paste is what I did as well.  I did also check the box for all official cards/sets, but I didn't think that would affect it. White cards seem to be there.

![cah3](https://user-images.githubusercontent.com/34435330/33822429-82c06a88-de25-11e7-9cd3-6467bcff6cab.PNG)

Believe me, if I wasn't stumped, I wouldn't be here bothering you. Like, I figured out the reason the music cog wasn't working for me by looking through the code and fixed that alright (ffmpeg and path needed). If the format isn't what's wrong with the deck file, I have no other ideas.

**Comment by corpnewt** [comment]
Alright - so I've slept for a few hours, and then went ahead and pulled fresh json data from the site - and I still get both the "blackCards" and "whiteCards" keys in my new deck.json.  Can you send me your deck.json file so I can have a look at it?  There might be something amiss with the formatting.

**Comment by BleuSkie** [comment]
Just got back from work. Yeah, I can do that and thanks again for taking the time to help.
...ok, apparently I have no idea how to upload files here yet lol. I just put it in google drive.
https://drive.google.com/file/d/1hvUlqSIzl1UZA1a8uXbpfxlXr3js0TAL/view?usp=sharing

**Comment by corpnewt** [comment]
Well, this is interesting.  It loads up fine on my end.  *The rabbit hole goes deeper, it seems.*

**Comment by BleuSkie** [comment]
well rip me hahaha. I honestly don't know where to even look for a solution. Overall, it's not a big deal. The rest of your bot works for me and still has a lot of neat features, cah just wasn't in the "cards." If you think of something I could check or try, let me know. If not, no worries. Have a good night.

**Comment by BleuSkie** [comment]
Oh, I just closed and reloaded your bot to see if there was an update and it seems to work now :) I have no idea what changed, but it changed for the better lol. Consider this resolved :)))

**Comment by corpnewt** [comment]
Hey!  As long as it works haha.  I also pushed a few new changes *just now* - so I'd recommend updating again.  By all means if you run into any issues in the future - or just have some feature requests, let me know and I'll see what I can do!
