### ISSUE TITLE
bot not resbond + error

### ISSUE THREAD

**Issue by ixKrooZ** [corpnewt/CorpBot.py#45]
guys plz help me 
i get this error when i tried to start the bot
bot online but not resbond
this is the first error
`Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pac
ages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py/Main.py", line 56, in on_r
ady
    bot.load_extension("Cogs.CogManager")
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pac
ages\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py\Cogs\CogManager.py", line
9, in setup
    bot.add_cog(CogManager(bot, settings))
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py\Cogs\CogManager.py", line
8, in __init__
    discord.Color.blurple(),
AttributeError: type object 'Colour' has no attribute 'blurple'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pac
ages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py/Main.py", line 231, in on_
essage
`i tried to search in google nothing there
then bot came online then i tried $help or anything bot not resbond
only gave me this error
`    context = await bot.get_context(message)
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute
 'get_context'
`guys plz help me
and im not kid ,_,
im just noob on python
if u want money guys ill give u 4.45$ only have it on my Paypal account
and sorry for bad english

**Comment by camielverdult** [comment]
Update your discord.py library.

**Comment by camielverdult** [comment]
```
python3 -m pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
```

**Comment by ixKrooZ** [comment]
'python3' is not recognized as an internal or external command,
operable program or batch file.

**Comment by camielverdult** [comment]
Do you have python 3 installed? Did you set it up to work with Path?

**Comment by 1byte2bytes** [comment]
Can I get some info on what operating system you're using?

**Comment by ixKrooZ** [comment]
yeah already done 
python3.5.4 i think

**Comment by ixKrooZ** [comment]
```
Bot failed to load!
    No module named 'psutil'
Cats failed to load!
    No module named 'PIL'
ChatterBot failed to load!
    No module named 'pyquery'
Comic failed to load!
    No module named 'PIL'
ComicHelper failed to load!
    No module named 'pyquery'
GetImage failed to load!
    No module named 'PIL'
Giphy failed to load!
    No module named 'PIL'
Humor failed to load!
    No module named 'PIL'
Hw failed to load!
    No module named 'pyquery'
Jpeg failed to load!
    No module named 'PIL'
PCPP failed to load!
    No module named 'pyquery'
Printer failed to load!
    No module named 'PIL'
Reddit failed to load!
    No module named 'PIL'
Search failed to load!
    No module named 'pyquery'
Server failed to load!
    No module named 'pyquery'
Loaded 71 of 86 cogs.
Starting flush loop - runs every 300 seconds.

```

**Comment by 1byte2bytes** [comment]
Please run the install script for the bot. `Install.bat` for Windows or `install.sh` for other OSes.

**Comment by bisquitue** [comment]
`pip install PIL`

**Comment by ixKrooZ** [comment]
thanks guys
fainaly its work
<3333333333

**Comment by camielverdult** [comment]
yay

**Comment by ixKrooZ** [comment]
thank guys 
i just repair my python
then install again
<3333333333

**Comment by ixKrooZ** [comment]
guys i have last Q
where do

**Comment by ixKrooZ** [comment]
guys i have last Q
where do i set owner /
<_<

**Comment by 1byte2bytes** [comment]
$claim

**Comment by ixKrooZ** [comment]
ummm some commands not work <)<

**Comment by 1byte2bytes** [comment]
Please provide more information.

**Comment by ixKrooZ** [comment]
like $setup
and $admin

**Comment by ixKrooZ** [comment]
ummm i have new Q
i disable some commands
but when i go to another server not disabled
tell me how to disable it in all servers
or how to unload cog
