### ISSUE TITLE
Banned due to spam with Telephone

### ISSUE THREAD

**Issue by Baltire** [corpnewt/CorpBot.py#73]
Hello,

During the last night, my bot/client has been banned from Discord for spamming ads on servers. Some persons used the telephone module to spam each server which accepted their calls.

I tried with regex to avoid the bot sending links but I'm really confused and I don't want to get my bot banned anymore. If it happens again, they will probably disable my account too.

Thanks for your help.

**Comment by corpnewt** [comment]
Are you just looking to have links removed when sent via telephone?  I should be able to replace them with `link removed` or something similar.

**Comment by corpnewt** [comment]
I've pushed [a new commit](https://github.com/corpnewt/CorpBot.py/commit/58d7df46c8f5fb91d7058e4391fca84a5b3364c8) which should replace all urls and `discord.gg/whatever` text with `link removed` in telephone.  Hopefully this helps - if more needs to be done, let me know.

-CorpNewt
