### ISSUE TITLE
update help

### ISSUE THREAD

**Issue by Soheab** [corpnewt/CorpBot.py#74]
update help pls to the new cogs system

**Comment by corpnewt** [comment]
~~That's not an issue with the bot, nor a question I can answer.~~

Though the question remains vague - I [updated](https://github.com/corpnewt/CorpBot.py/commit/7b8ce6497f421661630b653e08038d7c936fadf8) the redis branch to [the new cog system](https://github.com/Rapptz/discord.py/commit/caf3d17d4aa3ce45435bb96ea6d99317bfef8618) this morning.  Hopefully that helps.

-CorpNewt

I have also [updated](https://github.com/corpnewt/CorpBot.py/commit/d64ccab2777f9ce975769df0fe2abad45cfaf8aa) the rewrite branch.

**Comment by Soheab** [comment]
> That's not an issue with the bot, nor a question I can answer.
> 
> Though the question remains vague - I [updated](https://github.com/corpnewt/CorpBot.py/commit/7b8ce6497f421661630b653e08038d7c936fadf8) the redis branch to [the new cog system](https://github.com/Rapptz/discord.py/commit/caf3d17d4aa3ce45435bb96ea6d99317bfef8618) this morning. Hopefully that helps.
> 
> -CorpNewt
> 
> I have also [updated](https://github.com/corpnewt/CorpBot.py/commit/d64ccab2777f9ce975769df0fe2abad45cfaf8aa) the rewrite branch.

ye thanks!
