### ISSUE TITLE
New help_formatter changes!

### ISSUE THREAD

**Issue by Soheab** [corpnewt/CorpBot.py#75]
After the cogs changes now there are changes to the help_formatter! 
here you can read them all https://gist.github.com/Rapptz/288294ca99fa1f042f0e39a92ddd88eb
xD

**Comment by corpnewt** [comment]
I just updated to the latest discord.py rewrite commit and the custom help formatter used in CorpBot is still working as intended. Is there an issue with your copy?

**Comment by Soheab** [comment]
yea if i do as example {prefix}help ascii it only shows the prefix and the args
edit: forgot to say, its a exact copy.
pic:
![image](https://user-images.githubusercontent.com/33902984/54465509-cac57b00-477b-11e9-85ee-1025c89cdf63.png)

**Comment by corpnewt** [comment]
Ah - yep, the names were missing.  I've updated both the redis and rewrite branches with fixes.  Let me know if anything else is amiss.

-CorpNewt

**Comment by Soheab** [comment]
nah, all fixed. Thanks! :D

**Comment by corpnewt** [comment]
Thanks for letting me know it broke 👍

**Comment by Soheab** [comment]
Hey im back with some issues xD -
1. the help thing doesn't show any aliases only the command name
2. doing (prefix)help (a command) doesn't show the command help only says the cogs it is and the footer

**Comment by Soheab** [comment]
> Hey im back with some issues xD -
> 
> 1. the help thing doesn't show any aliases only the command name
> 2. doing (prefix)help (a command) doesn't show the command help only says the cogs it is and the footer

nvm my things broke it, sryy

edit: the aliases not tho
and it sees subcommands as unknown

**Comment by corpnewt** [comment]
Based on your comments - this doesn't sound like an issue with my repo, but more an issue with whatever fork you're running?  Do make sure that if you're using my code, you credit me for what I've written.

I don't use aliases in my code - but my help for command/cog works as it should:

![image](https://user-images.githubusercontent.com/12772521/54493654-7667eb80-48a0-11e9-809b-6f414db43ad4.png)


-CorpNewt
