### ISSUE TITLE
getServerStat error

### ISSUE THREAD

**Issue by iDutchy** [corpnewt/CorpBot.py#76]
I do not have mongodb installed so it should convert to json, but I keep getting an error that it couldn't get getServerStat. I do have the get_cog in my __init__

**Comment by corpnewt** [comment]
~~Make sure you've updated your instance of the bot - the Settings.py file was updated to include the getServerStat() function in the rewrite branch a few weeks ago. Shutting the bot down fully then restarting it may also help.~~

I just looked through my commits - I was thinking of the [get|set|del]GlobalStat() functions added [here](https://github.com/corpnewt/CorpBot.py/blob/d64ccab2777f9ce975769df0fe2abad45cfaf8aa/Cogs/Settings.py#L686-L695).  

` I keep getting an error that it couldn't get getServerStat. I do have the get_cog in my init` Can you send the error?  That function has been implemented in the Settings.py module for a *long* time at this point, and shouldn't be causing issues.

-CorpNewt

**Comment by iDutchy** [comment]
`  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/bin/CharlesBot/cogs/TempRole.py", line 406, in addtemprole
    if self.settings.getServerStat(ctx.message.guild, "SuppressMentions"):
AttributeError: 'NoneType' object has no attribute 'getServerStat'`

**Comment by corpnewt** [comment]
Looks like your Settings module is not loaded.  When the TempRole module is loaded, it stores a reference to the Settings instance [here](https://github.com/corpnewt/CorpBot.py/blob/rewrite/Cogs/TempRole.py#L21).  With your error, it appears that the Settings module is either absent or fails to initialize.  Per the CogManager, the Settings module is always instantiated prior to other modules via the following [code snippet](https://github.com/corpnewt/CorpBot.py/blob/rewrite/Cogs/CogManager.py#L89):

```py
	def _load_extension(self, extension = None):
		# Loads extensions - if no extension passed, loads all
		# starts with Settings, then Mute
		if extension == None:
			# Load them all!
			self.bot.load_extension("Cogs.Settings")
```

That code is initially called [here](https://github.com/corpnewt/CorpBot.py/blob/rewrite/Main.py#L61) - and while the CogManager appears to load without a reference to the Settings module - when the `_load_extensions()` function is called, it loads Settings and Mute first, then reloads the rest (CogManager included) - so it's only without the reference for a short period of time.

My best guess is that your bot is either missing files, or something has been changed.

-CorpNewt

**Comment by iDutchy** [comment]
Thank you! I added the load_extension for the settings file before it loads all others and it works now! :D

**Comment by corpnewt** [comment]
What?  If you're working on a fork of the bot, this was never an issue with my copy anyway...  My code already has the `_load_extensions()` function called appropriately.

-CorpNewt

**Comment by iDutchy** [comment]
Yea, I added the cog to my own bot... I did not download all of your files

**Comment by corpnewt** [comment]
In the future that is necessary information for troubleshooting - and it is not an issue with my bot, so the issue does not belong here.

-CorpNewt

**Comment by iDutchy** [comment]
Sorry, thanks for your help tho!

**Comment by corpnewt** [comment]
No problem, best of luck with your bot - if you use modules from mine, do make sure to credit me for what I've written.

-CorpNewt

**Comment by iDutchy** [comment]
Will make sure to do that! :)

**Comment by DutchAssassin** [comment]
Hi, me again!

I updated my d.py lib and now I get the same error again...
