### ISSUE TITLE
I should be using this GitHub more

### ISSUE THREAD

**Issue by ayechief** [corpnewt/CorpBot.py#83]
![image](https://user-images.githubusercontent.com/10886930/63805664-3d857580-c91a-11e9-8aa9-6acb9cd26834.png)
you're*

**Comment by corpnewt** [comment]
That's a part of the AIML library the bot uses - not an issue with the python code.  If you can find that line in the thousands and thousands of lines of AIML, I'd encourage you to correct it and submit a PR.  But the chatbot isn't something I intend to spent a ton of time diving into as it's just for fun.

-CorpNewt
