### ISSUE TITLE
Do you have a Discord Support Server?

### ISSUE THREAD

**Issue by BaroDevelopment** [corpnewt/CorpBot.py#89]
Do you have a Discord Support Server?

**Comment by corpnewt** [comment]
Not specifically for supporting the bot, no.  Truly, CorpBot started as a small personal project, and is only something I work on in my spare time.

-CorpNewt

**Comment by BaroDevelopment** [comment]
Did u consider making one?

**Comment by corpnewt** [comment]
It is not something I currently have planned, no.

-CorpNewt

**Comment by BaroDevelopment** [comment]
```
{
    "prefix": "your_custom_prefix_here",
    "token": "your_token_here",
    "weather": "your_weather_api_key_here",
    "currency": "your_currency_api_key_here"
}
```

is this all? or are there more variables i can add?

**Comment by corpnewt** [comment]
You can add a `discogs` api key, as well as an `igdbkey` - but I don't believe the latter is updated for the current api. Most of the bot's settings are stored either in the settings.json file - or the redis database, depending on which you use.

-CorpNewt
