### ISSUE TITLE
DataBase refusing to either start or is broken 

### ISSUE THREAD

**Issue by MR-UNKNOWN2000** [corpnewt/CorpBot.py#99]
i followed what the text said in startbot.bat , i installed lavalink then created a folder with it and then started startbot.bat and it said it was starting the lavalink server but still seems like the server is refusing to start 
![image](https://user-images.githubusercontent.com/59323333/95675503-a35bad80-0b6c-11eb-92fe-dd1a11c9a337.png) and
![image](https://user-images.githubusercontent.com/59323333/95675521-bbcbc800-0b6c-11eb-95a4-1bc1a14d7f4e.png)
same problem

**Comment by corpnewt** [comment]
It does not appear that the lavalink server is running in your screenshot. It may not be configured properly.

-CorpNewt

**Comment by MR-UNKNOWN2000** [comment]
how can i configure it?
